# Generated by YCM Generator at 2020-06-09 16:48:00.795892

# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os
import ycm_core

flags = [
    '-x',
    'c',
    '-DFT2_BUILD_LIBRARY',
    '-DHAVE_ALLOCA_H',
    '-DHAVE_LIBC',
    '-DHX_MACOS',
    '-DSDL_VIDEO_METAL=0',
    '-DSDL_VIDEO_OPENGL_EGL=0',
    '-DSDL_VIDEO_OPENGL_ES2=0',
    '-DSDL_VIDEO_RENDER_METAL=0',
    '-DSDL_VIDEO_RENDER_OGL_ES2=0',
    '-DSDL_VIDEO_VULKAN=0',
    '-DTARGET_API_MAC_CARBON',
    '-DTARGET_API_MAC_OSX',
    '-D_THREAD_SAFE',
    '-D__APPLE__',
    '-Dgameplay_EXPORTS',
    '-I./binocle-c/src',
    '-I./binocle-c/src/binocle',
    '-I./binocle-c/src/binocle/core',
    '-I./binocle-c/src/deps',
    '-I./binocle-c/src/deps/fr-DHAVE_ALLOCA_H',
    '-I./binocle-c/src/deps/fr-D__APPLE__',
    '-I./binocle-c/src/deps/fr.dir/src/lstrlib.c.o',
    '-I./binocle-c/src/deps/freetype/.',
    '-I./binocle-c/src/deps/freetype/include',
    '-I./binocle-c/src/deps/freetype/include/config',
    '-I./binocle-c/src/deps/freetype/include/internal',
    '-I./binocle-c/src/deps/freetype/src/autofit',
    '-I./binocle-c/src/deps/freetype/src/psaux',
    '-I./binocle-c/src/deps/freetype/src/psnames',
    '-I./binocle-c/src/deps/freetype/src/raster',
    '-I./binocle-c/src/deps/freetype/src/sfnt',
    '-I./binocle-c/src/deps/freetype/src/smooth',
    '-I./binocle-c/src/deps/freetype/src/truetype',
    '-I./binocle-c/src/deps/glew/.',
    '-I./binocle-c/src/deps/glew/include',
    '-I./binocle-c/src/deps/glew/src',
    '-I./binocle-c/src/deps/kazmath/.',
    '-I./binocle-c/src/deps/kazmath/../lua/src',
    '-I./binocle-c/src/deps/libuv/include',
    '-I./binocle-c/src/deps/libuv/src',
    '-I./binocle-c/src/deps/libuv/src/unix',
    '-I./binocle-c/src/deps/lua/.',
    '-I./binocle-c/src/deps/lua/src',
    '-I./binocle-c/src/deps/ogg/.',
    '-I./binocle-c/src/deps/ogg/include',
    '-I./binocle-c/src/deps/parson/.',
    '-I./binocle-c/src/deps/physfs',
    '-I./binocle-c/src/deps/physfs/.',
    '-I./binocle-c/src/deps/rxi_map/.',
    '-I./binocle-c/src/deps/sdl/include',
    '-I./binocle-c/src/deps/sdl/include/configs/mac',
    '-I./binocle-c/src/deps/sdl/src/hidapi/hidapi',
    '-I./binocle-c/src/deps/sdl_mixer',
    '-I./binocle-c/src/deps/sokol',
    '-I./binocle-c/src/deps/stb_image',
    '-I./binocle-c/src/deps/vorbis/.',
    '-I./binocle-c/src/deps/vorbis/../ogg/include',
    '-I./binocle-c/src/deps/vorbis/include',
    '-I./binocle-c/src/deps/vorbis/lib',
    '-I./binocle-c/src/deps/vorbis/lib-D__APPLE__',
    '-I./binocle-c/src/deps/wren/../libuv/include',
    '-I./binocle-c/src/deps/wren/src/cli',
    '-I./binocle-c/src/deps/wren/src/include',
    '-I./binocle-c/src/deps/wren/src/module',
    '-I./binocle-c/src/deps/wren/src/optional',
    '-I./binocle-c/src/deps/wren/src/vm',
    '-I./binocle-c/src/deps/zlib/.',
    '-I./src',
    '-I./src/deps',
    '-I./src/deps/freetype',
    '-I./src/deps/glew',
    '-I./src/deps/kazmath',
    '-I./src/deps/libuv',
    '-I./src/deps/lua/src',
    '-I./src/deps/miniaudio',
    '-I./src/deps/ogg',
    '-I./src/deps/physfs',
    '-I./src/deps/sdl/include',
    '-I./src/deps/sdl_mixer',
    '-I./src/deps/sokol',
    '-I./src/deps/stb_image',
    '-I./src/deps/vorbis',
    '-I./src/deps/wren',
    '-I./src/deps/zlib',
    '-I./src/gameplay',
    '-std=c11',
    '-std=c99',
    '-std=gnu99',
    '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.p-D__APPLE__',
    '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk',
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.C', '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.H', '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }

def Settings( **kwargs ):
    language = kwargs[ 'language' ]
    if language == 'cfamily':
        return {
            'flags': flags
        }

    return {}
